#### WORKFLOW ####
# Name of the Workflow
name: CICD

# when does the workflow run
on: push
#### JOBS ####
jobs:
  code:
   #### STEPS ####
   runs-on: ubuntu-latest  #runner os
   steps: #steps
     - name: Code checkout
       uses: actions/checkout@v7  #actions
  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
     - name: Code Build
       run: echo "Docker todo"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: Code test
       run: echo "Code test done"
  deploy:
     needs: test
     runs-on: ubuntu-latest
     steps:
     - name: Code Deploy
       run: echo "Code deploy done"
