#### WORKFLOW ####
# Name of the Workflow
name: CICD

# when does the workflow run
on: push
#### JOBS ####
jobs:
  code:
   #### STEPS ####
   runs-on: ubuntu-latest
   steps:
     - name: Code checkout
       run: echo "Code checkout done"
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Code Build
       run: echo "Code build done"
  test:
    runs-on: ubuntu-latest
    steps:
     - name: Code test
       run: echo "Code test done"
  deploy:
     runs-on: ubuntu-latest
     steps:
     - name: Code Deploy
       run: echo "Code deploy done"
